### ISSUE TITLE
Подчистка репозитория

### ISSUE THREAD

**Issue by avasyukov** [IvanLudvig/mipt-programming#2]
Штатно в git-репозитории предполагается код + ресурсы + сценарии сборки. Там вполне может быть что-то ещё, если его наличие там уместно.

В данном случае точно стоит убрать:
- временные файлы сборки
- локальные настройки IDE, которые не переносимы между компьютерами

**Comment by IvanLudvig** [comment]
Внес изменения

**Comment by avasyukov** [comment]
Подтверждаю, что стало ок.

// Появились include-ы файлов *.cpp. В прошлой инкарнации в этом смысле было лучше.
// Но этот разговор мы только начали на семинаре вчера.
// И полный фэн-шуй в этом смысле будем наводить ближе к концу семестра.
// А на сейчас всё полностью ок.
